### ISSUE TITLE
Make installable via pip

### ISSUE THREAD

**Issue by niccokunzmann** [0-zM/hexagon#4]
In order to 

- add hexagon to the [python package index](http://pypi.python.org/)
- make it installable via `pip install hexagon`,

there needs to be a setup.py file. You can look [here](https://github.com/bottlepy/bottle/blob/master/setup.py) and [here](https://github.com/AllYarnsAreBeautiful/knittingpattern/blob/master/setup.py) for inspiration.

What is your idea?

**Comment by 0-zM** [comment]
Ich glaube nicht, dass hexagon unbedingt über pip installiert werden muss. Habe in letzter Zeit an einem anderen Projekt gearbeitet, wo das wahrscheinlich nützlicher wäre.
